services:
  pipemgr:
    build:
      context: .
    image: ghcr.io/picosh/pipemgr:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $HOME/.ssh/id_ed25519_pico_antonio:/key:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 1s
  httpbin:
    image: kennethreitz/httpbin
    command: gunicorn -b 0.0.0.0:3000 httpbin:app -k gevent --access-logfile -
    ports:
      - 3000:3000
    labels:
      pipemgr.enable: true
    depends_on:
      pipemgr:
        condition: service_healthy
